[build]
  command = "yarn build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"
  REACT_APP_GITHUB_API_KEY = "From netlify.toml (REACT_APP_)"
  REACT_APP_SERVICE_ID = "From netlify.toml (REACT_APP_)"
  REACT_APP_TEMPLATE_ID = "From netlify.toml (REACT_APP_)"
  REACT_APP_USER_ID = "From netlify.toml (REACT_APP_)"
